### PR TITLE
Fixes #351 - Added throw escalation event in modeler

### LINKED ISSUE #351: Missing bpmn elements in the web modeler
The web modeler is missing some elements : 

- Compensation Intermediate Throwing Event
- Transaction container 

Here is the related thread from the forum.

https://forum.flowable.org/t/compensation-intermediate-throwing-event/465

Thank you.

### PR DESCRIPTION
**Pull request by im-pratham**
#### Check List:
* Unit tests:  NA
* Documentation: NA

### CODE REVIEW

**Comment by im-pratham** [comment]
fixed #351

**Comment by kenasv** [comment]
https://flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#xml-representation-19

Where is the optional argument "activityRef"?





I am deploy new app with you commit, but I do not see optional argument "activityRef":

**Comment by im-pratham** [comment]
Compensation Activity Ref UI

Generated XML

The test cases for the json convertor were already present in source repo. See https://github.com/flowable/flowable-engine/blob/master/modules/flowable-json-converter/src/test/java/org/flowable/editor/language/ThrowCompensationEventTest.java.

**Comment by im-pratham** [comment]
@tijsrademakers @filiphr ready for review

**Comment by tijsrademakers** [comment]
Thanks for the PR!

**Pull request merged**
