### PR TITLE
Update Jackson to version 2.12.3.

### PR DESCRIPTION
**Pull request by PascalSchumacher**
New version of https://github.com/flowable/flowable-engine/pull/2812 as I can not reopen the pull request because of force pushing.

Not sure if this should be merged or if you like to wait until Spring Boot uses Jackson 2.12.

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks for figuring this out @PascalSchumacher. We'll have a look at it and try to resolve it. 

It is failing now because the `JavaTimeModule` was not registered, I think that it isn't done automatically. Looking at the failure it happens in testing, I think we can do better there, we aren't using java time in the production code.

**Comment by PascalSchumacher** [comment]
Hi Filip,

not sure what you mean. Should these tests be removed?

**Comment by filiphr** [comment]
>not sure what you mean. Should these tests be deleted?

No we don't need to delete them. We need to analyse why this error is happening.

**Comment by PascalSchumacher** [comment]
o.k., build is fixed.

**Comment by PascalSchumacher** [comment]
Hi Filip,

any feedback on this pull request?

**Comment by filiphr** [comment]
Thanks for the ping @PascalSchumacher. I am not sure that the custom Jackson object provider is the way to go for JsonUnit. We should review the tests.

In addition to that Spring Boot 2.4.5 still uses Jackson 2.11. I think that it is better to wait and upgrade the Jackson Dependency in the same time as the Spring Boot dependency. 

Let's leave this open until we do that.

**Comment by filiphr** [comment]
Thanks a lot for this @PascalSchumacher. I have manually merged it in https://github.com/flowable/flowable-engine/commit/074a82d6b7c3e88a552d5c55157373f193450a24.

I've fixed the tests that were causing the problem with Jackson and removed the `JavaTimeObjectMapperProvider`(s). Your PR also inspired me and I did https://github.com/flowable/flowable-engine/commit/52255d018795a62c94efae4efda17f18b4163aef

**Pull request closed without merging**
