### PR TITLE
Change to dynamic context root for ui-idm-app #1022

### PR DESCRIPTION
**Pull request by vzickner**
Use current `window.location.pathname` to figure out the current context root instead of hardcoded context roots. Tested with Mozilla Firefox and Google Chrome.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
I guess the same should be done for the other ui-apps (modeler, admin, task).

**Comment by vzickner** [comment]
Hi @PascalSchumacher, I have added also the adaption for task and modeler. For admin there is no `app-cfg.js`. Unfortunately, flowable-task is using subfolder, therefore it was necessary to enhance the regex for filtering. It's now not that readable as it was before.

**Comment by martin-grofcik** [comment]
I 've tested several context path configurations. In the case when IDM app is mapped to the root.
I am not able to login. POST to https://app/authentication fails.

**Comment by vzickner** [comment]
Hi @martin-grofcik, I improved the regex to also handle root as potential deployment location. Previously, in that case, the context root was set to `/` and all REST endpoints are using `context-root + /path/to/resource`. It tried to call `//path/to/resource` which is translated to `http://path/to/resource`. To avoid this it is necessary that the context-root does not end with a slash.

**Comment by tijsrademakers** [comment]
@martin-grofcik could you test the updates of Valentin?

**Pull request merged**
