### PR TITLE
Fixing a modeler problem: property checkboxes are invisible

### PR DESCRIPTION
**Pull request by jaam**
Due to a wrong configuration boolean properties couldn't be modified in modeler because the checkbox component couldn't be rendered

#### Check List:
* Unit tests: NA
* Documentation: NA

### CODE REVIEW

**Comment by douglascrp** [comment]
This is still a problem with the Gateway's Default Condition property, as described at #2661

**Comment by filiphr** [comment]
@douglascrp this fix is not released. Did you try a snapshot version or are you talking about 6.6.0

**Comment by douglascrp** [comment]
@filiphr Right... got it, so that is it, as I'm using the 6.6.0 version.

I am going to build my own snapshot version and give it a try.

Thank you.

**Comment by douglascrp** [comment]
@filiphr indeed, the snapshot version fixes it.

Thank you

**Pull request merged**
