### PR TITLE
New form fields for layouting

### PR DESCRIPTION
**Pull request by ttonl**
CSS styles for horizontal line added.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi,

Could you check the PR diff, because I see a lot of files that are already changed with the previous PR you did.

**Comment by ttonl** [comment]
Hi tijs,
yeah in this PR the previous commit is included. So there aren't any new changes in the old one (3c9f2026a94585a34b3daa764d1b078b74bccba8). 

The latest commit just adds the style for the horizontal line to the modeler and task application.

**Comment by tijsrademakers** [comment]
Hi, 

That's good, but can you make sure the PR only includes the style changes? I would expect just one or two files in the diff here on Github.

**Comment by PascalSchumacher** [comment]
@ttonl You should be able to reduce this pull request to just to just dece73f by rebasing with

`git rebase -i HEAD~2`

choosing to drop 3c9f202

and then force pushing with `git push -f`

**Pull request merged**
