### PR TITLE
init basic translate pt_BR for flowable by @ambientelivre

### PR DESCRIPTION
**Pull request by marciojv**
Hi, I'm starting the translation for  Brazilian Portuguese for the flowable, there is still a lot of work to do, but I would like to know if this contribution is of interest to the project.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi, we can merge translations to the project. In the user guide we state that only English is maintained by the Flowable development team.

**Comment by marciojv** [comment]
Thanks, I'll be working on it for the next 30 days and sending the pull requests!

**Comment by yvoswillens** [comment]
@marciojv could you create a new PR when you're finished with translating?

**Comment by marciojv** [comment]
Yes! :)

**Comment by yvoswillens** [comment]
Okay.. Then I'll close it for now.

**Pull request closed without merging**
