### PR TITLE
Run distro profile on travis

### PR DESCRIPTION
**Pull request by PascalSchumacher**
For even better coverage than https://github.com/flowable/flowable-engine/pull/686.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
@PascalSchumacher Travis can't run more modules in a stable way. There are memory and full test time issues that prevents this (at least when we test some months back).

**Comment by PascalSchumacher** [comment]
@tijsrademakers Thanks for letting me know. 👍 😃

It probably won't be successful, but I'd like to give it a try. (Travis timeouts have been increase recently.)

**Comment by PascalSchumacher** [comment]
Looks like `flowable-ldap-configurator` need to be update to match recent changes else where in the code base. Tests fail with:

```
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'idmProcessEngineConfigurator' of bean class [org.flowable.spring.SpringProcessEngineConfiguration]: Bean property 'idmProcessEngineConfigurator' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243)
	at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:437)
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:292)
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:280)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1564)
	... 35 more
```

**Comment by PascalSchumacher** [comment]
Note: I created separate pull requests for the bugfix and testfix commits in this pull request. I will rebase this pull request after/if they are merged.

**Comment by PascalSchumacher** [comment]
Rebased onto master.

**Comment by PascalSchumacher** [comment]
Not sure if https://github.com/flowable/flowable-engine/pull/687/commits/bca3bcf7ca98e3d54dcd1c04e5a2118a7b4f48b8 is correct, but this tests fails a lot, so something should be done to make it more stable.

**Comment by tijsrademakers** [comment]
Running the check profile is sufficient for a first test run with Travis to my opinion. We have the QA builds on Jenkins for more extensive testing.

**Comment by PascalSchumacher** [comment]
I would opt for maximum coverage on travis and run the distro profile, but running check is a big step in the right direction (much better than the much more limited compile/test coverage run before). Thanks for enabling the check profile on travis!

**Comment by tijsrademakers** [comment]
Yes, I think the goal should be to run the distro profile. But let's first see if the check profile runs stable over a couple of weeks. If it's working fine, we'll switch to the distro profile.

**Comment by PascalSchumacher** [comment]
Great! Let's see.

The only failures during the last ten days were `org.flowable.spring.test.jobexecutor.SpringAsyncExecutorTest` which failed with a `FlowableOptimisticLockingException` I sometimes get this locally, so I do not think it is related to travis.

**Pull request closed without merging**
