### PR TITLE
Support UUID value type in flowable-rest API (#3856)

### LINKED ISSUE #3856: REST API responses with null value for UUID variable types
**Describe the bug**
The REST API method `flowable-rest/service/query/historic-variable-instances` returns null as value of variable of type `uuid`
```
        {
            "id": "85077ed6-d62c-11ee-ae20-86c5a61b31b3",
            "processInstanceId": "827254fd-d62c-11ee-ae20-86c5a61b31b3",
            "processInstanceUrl": "http://test-server/flowable-rest/service/history/historic-process-instances/827254fd-d62c-11ee-ae20-86c5a61b31b3",
            "taskId": null,
            "executionId": "827254fd-d62c-11ee-ae20-86c5a61b31b3",
            "variable": {
                "name": "animalId",
                "type": "uuid",
                "value": null,  //<-------- here is unexpected null
                "scope": "global"
            }
        },
```

**Expected behavior**
The UUID variable value should be serialized as string like
```
"value": "201d919d-9974-4813-8628-ae815f311678",
```

**Code**
/flowable-rest/src/main/java/org/flowable/rest/service/api/RestResponseFactory.java
method `createRestVariable` is searching for a convertor list of `variableConverters`. But there is no variable converter for variable type `org.flowable.variable.service.impl.types.UUIDType` so the createRestVariable returns a RestVariable with null value.

**Additional context**
Problem was reproduced on Flowable 6.8.0, but I checked the sources and it exists on main branch too.

Would be nice to have a fix in next 7.0.x release as we are going to upgrade to that version soon.

I am going to provide a Pull request for the fix soon.

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Fixes #3856 

#### Check List:
* Unit tests: NO
* Documentation: NO

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Thanks for the PR, can you also add this variable converter to the cmmn and dmn engine REST APIs?

**Comment by pvojtechovsky** [comment]
> can you also add this variable converter to the cmmn and dmn engine REST APIs?

Makes sense, good idea. I just did it now.

**Comment by edee111** [comment]
@tijsrademakers Is there something blocking this PR? Any idea when will it be accepted?

**Comment by tomsvet** [comment]
> @edee111, it would be good if there were some tests for it as well

@filiphr I added some tests for it.

**Comment by jkremlacek** [comment]
@tijsrademakers @filiphr Is there anything else that needs to be added to this PR in order to be accepted?

**Comment by pvojtechovsky** [comment]
Hi @filiphr ,  what is the problem with this PR please?

**Comment by tomsvet** [comment]
@tijsrademakers @filiphr Hello, when could this MR be merged, please?

**Comment by pvojtechovsky** [comment]
It is nearly 6 months since I spent my time to bring feature to the flowable project. 

It sounds to me like you are not interested in new features or may be this project is ill? Because having no response from maintainers for nearly 3 months doesn't sound healthy for me.

My trust into flowable project is decreasing. Is flowable project dying? Should I start to search for something more reliable? Could you please give me some inside, so I can understand what is happing here? 

Thank you, I hope all is good with you and this PR was just lost. Right?

**Comment by filiphr** [comment]
@pvojtechovsky the Flowable project is not dying.

The reason why this has not been merged yet is because we need to adjust all the not needed formatting changes that have been done as part of this PR.

e.g. there are `*` imports being used and we do not use in the project, there are also obsolete whitespace changes.

All of that means that we need to spend more work in integrating the PR and thus it takes a bit longer time. I was actually planning to do that this week (even before you wrote)

**Pull request merged**
