### PR TITLE
Added the potential starter fields for the proccess, working on the task

### PR DESCRIPTION
**Pull request by sibok666**
app to restrict the start of a process. modified the modeler app for
give app access to determined groups or users, to do : get the values of
app restriction saved to restrict the app access

### CODE REVIEW

**Comment by yvoswillens** [comment]
@sibok666 I haven't looked at it functionality-wise yet. But I see some strange indentations and some commented code. That needs to be fixed. Thanks

**Comment by sibok666** [comment]
Ok, @yvoswillens  I will do thesse adjustemnts today.

Thanks.

**Comment by sibok666** [comment]
@yvoswillens Updated the strange comments and indentation, anything to be changed for a succesful PR?

@tijsrademakers Any suggestions on the pendding to do : get the values of
app restriction saved to restrict the app access

Best regards

**Comment by tijsrademakers** [comment]
@sibok666 Thanks, can you make sure that all conflicts of this PR against master are resolved? Then I'll have a look at the pending to dos.

**Comment by sibok666** [comment]
@tijsrademakers im sorry I was bussy this days, now all the conflicts have been resolved.

I wait for your feedback.

Thanks.

**Comment by sibok666** [comment]
@tijsrademakers Hi Tijs, now the restrict app access is now complete and working. I've included the spanish translation files for the ui Apps: idm-app, task-app, modeler-app, admin-app

There are some text that are hardcoded, I'll work on them later, for implement the translation.

The restrict app access work by providing the users sepparated by commas on app definition, and providing the groups separated by commas on app definition.

This features are related to the issues #240 and #241

I'll wat for your feed back.

Thanks.

**Comment by tijsrademakers** [comment]
Merged manually. Have a look at the commit (https://github.com/flowable/flowable-engine/commit/f8d542cbc04df4507dacfe202cf85e9e7aa35678), let me know if you see any issues with the changes.

**Comment by sibok666** [comment]
Everithing looks fine, Best regards

**Pull request closed without merging**
