### PR TITLE
Make camel tests more stable

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi Pascal,

Last week we had a failing Travis build with the error message "More than 4mb error logging, the job is expected to have a recurring error". Do you think we won't get this error message a lot more when changing to the distro profile?

**Comment by PascalSchumacher** [comment]
Sorry, the distro profile commit was just in order to test this on travis. I will remove it.

**Comment by PascalSchumacher** [comment]
Hi Tijs,

I removed the distro change commit from the pull request.

**Comment by tijsrademakers** [comment]
Thanks, just wanted to verify ;-)

**Pull request merged**
