### PR TITLE
Update All-in-One Dockerfile

### PR DESCRIPTION
**Pull request by unamanic**
Corrects Issue #1859 and #1856 in all-in-one container, but migrating to the regular alpine base image and adding fonts.

### CODE REVIEW

**Comment by filiphr** [comment]
Awesome work @unamanic. Just thinking out loud now. Why not switch to AdoptOpenJDK 11 docker image?

**Comment by unamanic** [comment]
@filiphr I don't see any reason not to, since JDK 11 is the next LTS release.  However this fix should probably get back-ported to 6.4.2, since the published images contain both of these issues.

**Comment by unamanic** [comment]
Updated Docker image to use  AdoptOpenJDK 11

**Comment by PascalSchumacher** [comment]
I guess this pull request was made redundant by https://github.com/flowable/flowable-engine/commit/0d5e6309f2fda95c60d298ef8cd0bc69bdcd4e66?

**Comment by yvoswillens** [comment]
We're currently testing the referred commit. It's a bit different than this PR. 
When it's verified I will comment on this and close it.

**Comment by unamanic** [comment]
I’m not certain the other pull request solves the issue with JavaScript script tasks, since Nashorn is one of the things pulled from the slim image.

**Comment by yvoswillens** [comment]
for the jdk8 alpine slim that was the case; for the jdk11 alpine slim not.

**Comment by bwangfdu** [comment]
I find current adoptopenjdk/openjdk11:alpine seems not working with Flowable-rest-app 6.4.2 release version. When I start the jar file with "java -jar", it exit with "segmentation fault". The alpine base image and adding openjdk11 with apk works fine.

**Comment by unamanic** [comment]
This Pull request no longer required.

**Pull request closed without merging**
