### PR TITLE
Pre upgrade script

### PR DESCRIPTION
**Pull request by martin-grofcik**

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi Martin,

I like the idea of execution logic before (and I think also after) each migration. Instead of only supporting script, could you maybe make this more flexible, so that you can also execute a Java class or an expression like we do in several other places?

**Comment by gro-mar** [comment]
Hi Tijs,

yes, I am just checking whether the idea is good to merge. I will extend it.

Martin

**Comment by gro-mar** [comment]
May be it could evolve into some kind of "migration" process....

 `start` --> `Upgrade script/javadelegate.....` --> `mapping` --> `end`

and we can benefit from the audit trail...... .

**Comment by tijsrademakers** [comment]
Cool Martin, I think the idea of having a possibility to add pre upgrade logic is very useful. Will you work on the java delegate / expression support in this same PR?
Supporting migration processes is more a matter of how someone would like to implement it I think, it's already possible to do it in a BPMN process.

**Comment by martin-grofcik** [comment]
Yes, I will try.

**Comment by martin-grofcik** [comment]
@tijsrademakers Hi Tijs. Any update on this?

**Comment by tijsrademakers** [comment]
Hi Martin, the changes look good. I think it would make sense to also add an after migration script /  class / expression as well. With that this PR would be complete and we can merge it master.

**Comment by martin-grofcik** [comment]
https://github.com/flowable/flowable-engine/pull/2116

**Comment by tijsrademakers** [comment]
Closing because of new PR #2116

**Pull request closed without merging**
