### PR TITLE
Java 9 compatiblity

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Rebased `jdk9` branch onto `master`.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Mule does not work if https://forums.mulesoft.com/questions/76918/mule-java-9-any-issues.html it will not work soon.

**Comment by PascalSchumacher** [comment]
If mule test are excluded I can successfully build and test everything besides `flowable-osgi` (test won't run because of unmet requirements),

**Comment by PascalSchumacher** [comment]
`flowable-osgi` tests also fail on java 8, so I guess the failure is not caused by java 9 but by other changes (dependency updates?).

I have excluded the `flowable-osgi` modules from the build to demonstrate what currently works.

**Comment by tijsrademakers** [comment]
Hi Pascal,

I checked the flowable-osgi module this morning locally and there the tests were running ok. Do you get errors running the tests locally?

**Comment by PascalSchumacher** [comment]
Hi Tijs,

guess you are referring to master? On master the flowable-osgi test pass locally for me. Sadly on this branch they do not.

**Comment by tijsrademakers** [comment]
Ah ok, yes I was referring to master.

**Comment by PascalSchumacher** [comment]
OSGI Tests now work on java 8 (https://github.com/flowable/flowable-engine/pull/761/commits/f69a9d2b98953200e2fdba8e5fc4b230d5f91f20), but not yet on java 9

**Comment by PascalSchumacher** [comment]
OSGI tests now work on java 9 (https://github.com/flowable/flowable-engine/pull/761/commits/8cd12ee3c345eed0ccbd1c3dbd4cebebbaec954a)

**Comment by PascalSchumacher** [comment]
I separated commits for changes not related to java 9 compatibility into two other pull requests: https://github.com/flowable/flowable-engine/pull/765 and https://github.com/flowable/flowable-engine/pull/766. I will remove these commits from this branch when/if the other commits are merged.

**Comment by PascalSchumacher** [comment]
Rebased onto master.

**Comment by PascalSchumacher** [comment]
You are welcome.

Thanks for merging!

**Comment by PascalSchumacher** [comment]
By the way, it would be great if somebody could update the jdk9 wiki page: https://github.com/flowable/flowable-engine/wiki/JDK-9

Thanks!

**Pull request merged**
