### PR TITLE
Isarray null enhancement

### PR DESCRIPTION
**Pull request by qiudaoke**
#### Check List:
* Unit tests: YES / NO / NA
* Documentation: YES / NO / NA

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks for the PR @qiudaoke. Have you seen NPE in the places where you did the changes? Not every place can have a null value arriving at it, in some places it is completely OK to not do a null check

**Comment by qiudaoke** [comment]
> Thanks for the PR @qiudaoke. Have you seen NPE in the places where you did the changes? Not every place can have a null value arriving at it, in some places it is completely OK to not do a null check

When the customer uses it, it is scanned by the code scanning tool

**Comment by filiphr** [comment]
Closing this since none of the places can lead to an NPE.

Some places use `JsonNode#path` which never returns `null` and some other places use the iteration of `ObjectNode#fields` and those cannot have a `null` value. If it is `null` then it would be `NullNode`.

Which code scanning tool is reporting this?

**Comment by qiudaoke** [comment]
We can judge that these codes will not cause NPE, but Alibaba java coding guidelines tool will think that it will cause NPE
@filiphr

**Comment by filiphr** [comment]
@qiudaoke if the tool is saying that there can be an NPE there, then I would consider this as a bug in the tool. We use `JsonNode#path` on purpose in order to avoid null checks

**Pull request closed without merging**
