### PR TITLE
CountingTask (similar to the CountingExecution) 

### PR DESCRIPTION
**Pull request by motorina0**
For more details please check #123

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
I think that the db upgrade scripts need to be reviewed as my quick scan noticed that for db2 and hsql tha the same column is added twice.

<pre>
 +alter table ACT_RU_TASK add column VAR_COUNT_ integer;
 +alter table ACT_RU_TASK add column VAR_COUNT_ integer;
</pre>
 
I think that the second one should be `ID_LINK_COUNT_ `

**Comment by motorina0** [comment]
Sorry for that.  I will review them immediately.

**Comment by motorina0** [comment]
Done. Committed & pushed.
I will review the rest of the SQL scripts again.

**Comment by dbmalkovsky** [comment]
Thanks for the quick turnaround.

A question for the group:  is this something that should be committed at this time (being in Release Candidate stage) as it includes modifying the database schemas or should it wait for the next development track?

**Comment by tijsrademakers** [comment]
I think we can still include it for the 6.0 release as it's based on the execution count change. But it needs some testing before it can be merged, so will take a few days.

**Pull request merged**
