### PR TITLE
Document BPMN REST API - Dead letter jobs

### PR DESCRIPTION
**Pull request by remibantos**
Document Dead letter jobs BPMN REST API mentioned here:
- https://forum.flowable.org/t/how-i-can-continue-a-task-of-retry-times-exhaust/4200
- https://forum.flowable.org/t/deadletter-jobs-vs-rest-api/2496

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Was the deletion of the `docs/userguide/src/zh_CN/bpmn/ch14-REST.adoc` and `docs/userguide/src/zh_CN/bpmn/ch15-Cdi.adoc` really intended?

**Comment by remibantos** [comment]
> Was the deletion of the `docs/userguide/src/zh_CN/bpmn/ch14-REST.adoc` and `docs/userguide/src/zh_CN/bpmn/ch15-Cdi.adoc` files really intended?

Yes, for zh_CN locale there were 2 versions with different chapters for REST and CDI documentation, so I tried to clean-up this.
For REST it looks OK as the two files were actually in english. However it looks like I kept the wrong one (English) for Cdi.

**Comment by tijsrademakers** [comment]
@remibantos would it be possible to do a small PR to set the CDI one right for Chinese?

**Comment by remibantos** [comment]
@tijsrademakers sure, I am doing that

**Comment by remibantos** [comment]
See PR #1864

**Pull request merged**
