### PR TITLE
The sequenceFlow name in modler does not display bug

### PR DESCRIPTION
**Pull request by qiudaoke**
I defined a process in the modler designer. Then I deploy the process, which does not display the name of the sequence flow in the ACT_GE_BYTEARRAY table

My process is as follows:
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.flowable.org/processdef">
  <process id="f" name="f" isExecutable="true">
    <documentation>f</documentation>
    <startEvent id="startEvent1"></startEvent>
    <userTask id="sid-B1F233CD-C2A3-45E1-A67D-582EFC189E4B" name="userTask1"></userTask>
    <userTask id="sid-14D3C994-A0F7-46B2-A440-A054DE886EC4" name="userTask2"></userTask>
    <endEvent id="sid-222145BB-442B-4EFE-9AF9-A560AD0DA0AE"></endEvent>
    <sequenceFlow id="sid-81F46558-CC0A-4C7D-AD6E-F803C371F9FF" name="start-userTask1" sourceRef="startEvent1" targetRef="sid-B1F233CD-C2A3-45E1-A67D-582EFC189E4B"></sequenceFlow>
    <sequenceFlow id="sid-74C1EB18-B8B7-4F9D-9D30-C6903FCA323A" name="userTask1-userTask2" sourceRef="sid-B1F233CD-C2A3-45E1-A67D-582EFC189E4B" targetRef="sid-14D3C994-A0F7-46B2-A440-A054DE886EC4"></sequenceFlow>
    <sequenceFlow id="sid-EA8CF180-8411-4D9F-8F4F-A604FD961DDE" name="userTask2-end" sourceRef="sid-14D3C994-A0F7-46B2-A440-A054DE886EC4" targetRef="sid-222145BB-442B-4EFE-9AF9-A560AD0DA0AE"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_f">
    <bpmndi:BPMNPlane bpmnElement="f" id="BPMNPlane_f">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="30.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-B1F233CD-C2A3-45E1-A67D-582EFC189E4B" id="BPMNShape_sid-B1F233CD-C2A3-45E1-A67D-582EFC189E4B">
        <omgdc:Bounds height="80.0" width="100.0" x="175.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-14D3C994-A0F7-46B2-A440-A054DE886EC4" id="BPMNShape_sid-14D3C994-A0F7-46B2-A440-A054DE886EC4">
        <omgdc:Bounds height="80.0" width="100.0" x="420.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-222145BB-442B-4EFE-9AF9-A560AD0DA0AE" id="BPMNShape_sid-222145BB-442B-4EFE-9AF9-A560AD0DA0AE">
        <omgdc:Bounds height="28.0" width="28.0" x="630.0" y="164.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-EA8CF180-8411-4D9F-8F4F-A604FD961DDE" id="BPMNEdge_sid-EA8CF180-8411-4D9F-8F4F-A604FD961DDE">
        <omgdi:waypoint x="519.9499999998277" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="630.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-81F46558-CC0A-4C7D-AD6E-F803C371F9FF" id="BPMNEdge_sid-81F46558-CC0A-4C7D-AD6E-F803C371F9FF">
        <omgdi:waypoint x="59.949999435861024" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="174.9999999999723" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-74C1EB18-B8B7-4F9D-9D30-C6903FCA323A" id="BPMNEdge_sid-74C1EB18-B8B7-4F9D-9D30-C6903FCA323A">
        <omgdi:waypoint x="274.95000000000005" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="420.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
`
I think this is probably a bug.

before the change
image

after commit
image

### CODE REVIEW

**Comment by qiudaoke** [comment]
@tijsrademakers 
Can we combine this PR?

**Comment by tijsrademakers** [comment]
Thanks for the PR. There are quite a number of cases you can have for a sequence flow, like bended arrows, arrows going in the upward or downward direction etc. I think we need to think about all these cases as well. Also, when the DI information contains the Label info, then it will be drawn in the diagram already. Did you try to include the Label DI information?

**Comment by qiudaoke** [comment]
@tijsrademakers 

   I redefined a process.
The flowchart is shown below.
image

The two sequenceFlow has the following Label DI information like this:
 

>  <bpmndi:BPMNEdge bpmnElement="flow1" id="BPMNEdge_flow1">
>         <omgdi:waypoint x="137.0" y="190.0"></omgdi:waypoint>
>         <omgdi:waypoint x="137.0" y="137.0"></omgdi:waypoint>
>         <omgdi:waypoint x="322.0" y="137.0"></omgdi:waypoint>
>         <omgdi:waypoint x="322.0" y="180.0"></omgdi:waypoint>
>         **<bpmndi:BPMNLabel>
>           <omgdc:Bounds height="13.0" width="100.0" x="140.0" y="151.0"></omgdc:Bounds>
>         </bpmndi:BPMNLabel>**
>       </bpmndi:BPMNEdge>
>       <bpmndi:BPMNEdge bpmnElement="flow2" id="BPMNEdge_flow2">
>         <omgdi:waypoint x="322.0" y="235.0"></omgdi:waypoint>
>         <omgdi:waypoint x="322.0" y="360.0"></omgdi:waypoint>
>         <omgdi:waypoint x="401.0" y="360.0"></omgdi:waypoint>
>         <omgdi:waypoint x="473.0" y="360.0"></omgdi:waypoint>
>         <omgdi:waypoint x="472.0" y="235.0"></omgdi:waypoint>
>         **<bpmndi:BPMNLabel>
>           <omgdc:Bounds height="13.0" width="26.0" x="330.0" y="279.0"></omgdc:Bounds>
>         </bpmndi:BPMNLabel>**
>       </bpmndi:BPMNEdge>

The generated images are as follows:

image

This means that this is correct.
When I remove the label（
><bpmndi:BPMNLabel>
>           <omgdc:Bounds height="13.0" width="100.0" x="140.0" y="151.0">
>           </omgdc:Bounds>
>         </bpmndi:BPMNLabel>）, 
I generated images again. The generated images are as follows:
image

When I add the following code：

**else {
                    GraphicInfo lineCenter = getLineCenter(graphicInfoList);
                    processDiagramCanvas.drawLabel(sequenceFlow.getName(), lineCenter, false); 
                }**
I generated images again. The generated images are as follows:
image


### When we use the modler designer to draw the process, sequenceFlow does not generate Label DI information.

**Comment by tijsrademakers** [comment]
Ok thanks for the clear explanation. We could enable the option to also include the sequence flow name in case there's no Label DI, but you need to be able to switch it off and on (default should be switched off for backwards compatibility). So we need to add an option in the process engine configuration as part of this PR.

**Comment by qiudaoke** [comment]
@tijsrademakers 
hi,
I added an enableIncludeSequenceNameWhenNoLableDi property to the process engine configuration.
And I used the enableIncludeSequenceNameWhenNoLableDi switch property in the ProcessDiagramGenerator class.
Is there anything else that needs good advice to improve?
thanks

**Comment by tijsrademakers** [comment]
@qiudaoke thanks for your changes, that works well. You made a small typo with "enableIncludeSequenceNameWhenNoLableDi". It should be "enableIncludeSequenceNameWhenNoLabelDi". Maybe we can change the name a bit, to be like "drawSequenceFlowNameWithNoLabelDI" ?

**Comment by qiudaoke** [comment]
@tijsrademakers 
I modified enableIncludeSequenceNameWhenNoLableDi to drawSequenceFlowNameWithNoLabelDI. Thank you

**Comment by tijsrademakers** [comment]
Thanks!

**Pull request merged**
