### PR TITLE
Closing inputStream after process auto deployment.

### PR DESCRIPTION
**Pull request by hidertanure**
I was having some trouble with hot deployment on tomcat after integrate my application with Flowable.
I that case, Flowable was letting all my .bpmn20.xml files open, preventing the server to made the deployment. Needing to stop the server before make a new deploy.

### CODE REVIEW

**Comment by hidertanure** [comment]
DeploymentBuilderImpl.java, this method public DeploymentBuilder addZipInputStream(ZipInputStream zipInputStream);

It is using the IoUtil.readInputStream expecting to keep the stream open. It is a wrong responsibility to the method. I sujest to create an another IoUtil.readInputStream to keep stream open explicity.

**Comment by tijsrademakers** [comment]
Hi,

Thanks for the PR, I understand your point. But we already take care of closing the input streams when using the IoUtil.readInputStream method in most cases I've looked at. I think we need to find the reason why it wasn't closed properly in your usage and explicitly close it there instead.
Do you know where it didn't do that in your case?

**Comment by hidertanure** [comment]
Hi, i glad to help.

In my case it was leaving open when i just put a .bpmn20.xml file in the process resource folder. When the deploy runs it leave the .xml file locked.

Thats is why i commited the code with the properly close on the read method like the others.

Looking on this test failure, it is using the read method in a wrong way. I sugest to change it, for example, creating a new Stream for the zipEntry to get the bytes.

Or change method name to express explicitly this responsability, to leave the stream open.

What do you think?

**Comment by hidertanure** [comment]
Submitting corrections on "addZipInputStream" methods as suggested.

> I sugest to change it, for example, creating a new Stream for the zipEntry to get the bytes.

**Comment by filiphr** [comment]
@hidertanure I would suggest that you inspect the call hierarchy of the method and appropriately close the streams there. One if the locations is the deployment strategies

**Comment by hidertanure** [comment]
I totaly agree with you. I’ll work on it.

What i was talking about responsability of the method it’s clear now after my last change. 
In a first look it’s seeams like that the Util had to close the stream, but it is exactly the opposit. The InputStream is a external managed resource, different from what is happening in the others Util’s methods.

A question. The openJdk build error it’s something related to the environment, wright?

**Comment by filiphr** [comment]
>What i was talking about responsability of the method it’s clear now after my last change.
In a first look it’s seeams like that the Util had to close the stream, but it is exactly the opposit. The InputStream is a external managed resource, different from what is happening in the others Util’s methods.

I don't think so. The read into bytes method should not close the stream. The other methods are not getting an input stream.

I would say that the current changes are not needed. We only need to make sure that the input stream is closed on the location where it is created.

**Comment by hidertanure** [comment]
> > What i was talking about responsability of the method it’s clear now after my last change.
> > In a first look it’s seeams like that the Util had to close the stream, but it is exactly the opposit. The InputStream is a external managed resource, different from what is happening in the others Util’s methods.
> 
> I don't think so. The read into bytes method should not close the stream. The other methods are not getting an input stream.
> 
> I would say that the current changes are not needed. We only need to make sure that the input stream is closed on the location where it is created.

I didn't make myself clear, but what i mean is the same. The Util don’t need to be change. In my first look i was wrong.

**Comment by filiphr** [comment]
>I didn't make myself clear, but what i mean is the same. The Util don’t need to be change. In my first look i was wrong.

OK, I didn't understand you well, sorry. 

Looking forward on the next commits then 😉

**Comment by hidertanure** [comment]
Sorry guys, i guess i made a mess with my commits...
I didn't undo the previous commit properly.
What's the best approach, closing this request and do a new fork?

**Pull request closed without merging**
