### PR TITLE
Speed up tests by removing JaCoCo

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Just a test, not sure if this has a positive effect on travis.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Definitely needs more work.

**Comment by filiphr** [comment]
Hey Pascal, just FYI. I haven't checked what improvement you are getting. However, we are going to merge the Java 11 PR really soon and we'll drop the testing on Java 9 and 10.

Do you think that these speed ups will improve Java 11 as well? How are the times compared to that PR?

**Comment by PascalSchumacher** [comment]
Hey Filip, glad to hear that the Java 11 PR will be merged soon. 😃 

With this PR I'm trying to reduce test execution time by reducing wait times. If it works it should help independent of the Java version in use.

**Comment by PascalSchumacher** [comment]
I think I found out why build on travis stared taking significantly longer (even timing out) a few days ago.

It was the addition of JaCoCo in this commit https://github.com/flowable/flowable-engine/commit/7d72dbd7a0a8ee7b2f03c158c7f7b8763480ddcf#diff-600376dffeb79835ede4a0b285078036R1052

When JaCoCo is removed the build on travis is 6-8 minutes faster.

**Comment by PascalSchumacher** [comment]
Will be solved in a different way, see: https://github.com/flowable/flowable-engine/commit/7d72dbd7a0a8ee7b2f03c158c7f7b8763480ddcf#r32323505

**Pull request closed without merging**
