### PR TITLE
Pull form variables from taskService if task is active

### PR DESCRIPTION
**Pull request by unamanic**
Fixes: #1743

#### Check List:
* Unit tests:  NO
* Documentation: NO

### CODE REVIEW

**Comment by unamanic** [comment]
I'm not entirely sure where sure where a test would go for this change.  There don't appear to be any form tests in flowable-engine, where this change is.

**Comment by tijsrademakers** [comment]
@unamanic thanks for the PR, but looking at the change, before the historic variables were fetched with the process instance id, but with your change this is now done with the task id. This means that process variables will not be taken into account anymore. I think that's not correct. Or did you test the historic case as well and was it working fine?

**Comment by unamanic** [comment]
@tijsrademakers, the referenced issue was caused by the fact that we were pulling by process id instead of by task.  When we pull with the process id instead of the task id, it pulls the current state of the element variable across the process.  This causes us to always get the last element that the process iterated through when creating parallel tasks.

With this change, process variables on completed tasks now show their state when they were completed instead of the most current state of the process in history.  Is that incorrect?  If so, I can change inactive tasks to fetch by process id instead.

**Comment by tijsrademakers** [comment]
@unamanic the problem before was that task specific variables were not taken into account, that is ok now with your change. But now process variables are not used anymore, only task specific variables. It should be a combination of both process and task specific variables, with task variables having precedence over process variables (if the same variable name is used for both).

**Comment by unamanic** [comment]
@tijsrademakers I'll introduce some code to explicitly bring in process variables.  Do you have any thoughts on where a unit test should go?

**Comment by unamanic** [comment]
[Parallel App.zip](https://github.com/flowable/flowable-engine/files/3640174/Parallel.App.zip)
The code now explicitly brings in any process variables that are not present on the task.  

I've attached the App I've been using for testing.  It uses Groovy to create a list called `items` and a process variable called 'p_var'.  It then flows to a parallel user task that iterates over `items` and gives each task the element variable `item`.

**Pull request merged**
