### PR TITLE
Optimize service task execution

### PR DESCRIPTION
**Pull request by cdeneux**
See issue #622

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi,

I understand the idea behind this PR, but adding a synchronized if check is not something that would be nice to have in a web service task. What could be an alternative solution is to cache the definition maps in a cache like it's done for the BpmnModels.

**Comment by cdeneux** [comment]
Hi Tijs,
Can you give me more pointers or entry points about the cache usefor BpmnModels ?
Thanks

**Comment by cdeneux** [comment]
Tijs,

Is it possible to add a new parameter to the method `ActivityBehaviorFactory.createWebServiceActivityBehavior(ServiceTask)` to transmit the current BPMN model at the creation of `WebServiceActivityBehavior`? And so, no more synchronization bloc is needed to load definition maps.

**Comment by tijsrademakers** [comment]
Hi,

Yes we can pass the BPMN model at the creation of the WebServiceActivityBehavior.
But that only removes the need for the BpmnModel bpmnModel = ProcessDefinitionUtil.getBpmnModel(execution.getProcessDefinitionId()); line right?
So that's the line outside the synchronized block, right?

**Comment by cdeneux** [comment]
The definition map loading requires only the BPMN model. And so, if pass the BPMN model at the creation of the `WebServiceActivityBehavior`, we can load definition maps through `fillDefinitionMaps(BpmnModel)` in the constructor. And so the synchronisation bloc is no more needed. The BPMN model is always needed by IO Specification for the execution.
```
   public WebServiceActivityBehavior(BpmnModel bpmnModel) {
        itemDefinitionMap.put("http://www.w3.org/2001/XMLSchema:string", ...);
        fillDefinitionMaps(bpmnModel);
    }

    public void execute(DelegateExecution execution) {

        BpmnModel bpmnModel = ProcessDefinitionUtil.getBpmnModel(execution.getProcessDefinitionId());
        FlowElement flowElement = execution.getCurrentFlowElement();

        ...
```

**Comment by tijsrademakers** [comment]
Ah ok, understood. Let me check if we can easily add the BpmnModel in the WebServiceActivityBehavior constructor and then I'll let you know.

**Comment by cdeneux** [comment]
Ok Tijs, I'll wait your feedback.

**Comment by tijsrademakers** [comment]
Hi, made the change to pass the BpmnModel

**Comment by cdeneux** [comment]
New PR #627 submitted including remarks of @tijsrademakers

**Pull request closed without merging**
