### PR TITLE
Add TaskHelper

### PR DESCRIPTION
**Pull request by marcus-nl**
Add TaskHelper to make creating custom task submission commands easier.

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
Why was the license comment block removed from TaskHelper.java?

**Comment by marcus-nl** [comment]
TaskHelper is a new class. I'll add the header.

**Comment by marcus-nl** [comment]
Any other comments before I resolve the merge conflict?

**Comment by tijsrademakers** [comment]
Hi Marcus, no if the merge conflict is resolved we'll merge the PR

**Comment by marcus-nl** [comment]
Done.

**Pull request merged**
