### PR TITLE
Process test

### PR DESCRIPTION
**Pull request by martin-grofcik**
the simple implementation of the process testing framework user interface for modelers.

### CODE REVIEW

**Comment by lucjross** [comment]
I read your blog and I think this would be very useful. What are the chances of this being merged?

**Comment by martin-grofcik** [comment]
Process debugger is merged as an experimental feature to 6.3.0. To enable it turn `flowable.experimental.debugger.enabled` property to true. After that you can find in in the flowable-task app -> process instance -> show diagram.
Recently added features are in the pull request https://github.com/flowable/flowable-engine/pull/980.
flowable-admin integration: Yes there are several possibilities how to implement debugger and admin app is one of them too. Let's see how the community will react on this feature.

**Comment by n0mer** [comment]
@martin-grofcik would you close this PR, since this feature is merged to 6.3.0?

**Comment by martin-grofcik** [comment]
The merged functionality is process debugger. This pull request still contains process testing framework implementation which is still not merged. That's why I am keeping it opened.

**Comment by tijsrademakers** [comment]
Closing outdated PRs

**Pull request closed without merging**
