### PR TITLE
#3109 collect multi hit policy

### PR DESCRIPTION
**Pull request by martin-grofcik**
#### Check List:
* Unit tests: YES
* Documentation: NA

### CODE REVIEW

**Comment by martin-grofcik** [comment]
@tijsrademakers @jbarrez @filiphr : Is there any reason why pull request is not merged?

**Review by yvoswillens — APPROVED** [review]

**Review by yvoswillens — CHANGES_REQUESTED** [review]
Hi @martin-grofcik 

The PR looks good.
One remark; Could you add some tests to check the behaviour of the modification of the CollectHitPolicy when `ProcessEngineConfiguration.alwaysUseArraysForDmnMultiHitPolicies` is `false`?

Thanks!

Yvo

**Comment by martin-grofcik** [comment]
Thanks @yvoswillens,

additional tests added.
Martin

**Comment by yvoswillens** [comment]
Hi @martin-grofcik 

Perhaps I'm missing something but I do not see that the additional tests set `ProcessEngineConfiguration.alwaysUseArraysForDmnMultiHitPolicies` to `false`

as done here; 

https://github.com/flowable/flowable-engine/blob/main/modules/flowable-dmn-engine-configurator/src/test/java/org/flowable/dmn/test/runtime/DmnTaskTest.java#L123

Regards,

Yvo

**Comment by martin-grofcik** [comment]
Hi @yvoswillens,

```
    protected void executeWithoutArrays(Runnable runnable) {
        processEngineConfiguration.setAlwaysUseArraysForDmnMultiHitPolicies(false);
        try {
            runnable.run();
        } finally {
            processEngineConfiguration.setAlwaysUseArraysForDmnMultiHitPolicies(true);
        }
```

and tests are e.g. `withRuleOrder_ensureOnlyOneRowIsHit_withoutArrays`, `collectHitPolicyNoAggregatorUseArrays_NoneHit_withoutArrays`, `withRuleOrder_ensureNoRowIsHit_withoutArrays`.

Is this what you meant?

Regards
Martin

**Comment by yvoswillens** [comment]
Hi @martin-grofcik 

right.. I see..
Looks okay.

Thanks.

**Pull request merged**
