### PR TITLE
592 Add Data Object support for Modeler

### PR DESCRIPTION
**Pull request by lsmall**
Added view and translation elements

Also fixed some conversion errors in model setValue()

https://github.com/flowable/flowable-engine/issues/592

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Great. 👍 

Just a few days ago I was telling my colleagues, that data object support for modeler would be really nice.

**Comment by tijsrademakers** [comment]
Hi Lori,

I've merged the PR with some minor changes. I've reverted the changes to the JSON property naming because there could be issues with backward compatibility. Could it be that some parts are missing in this PR? Because there's no DataObject element added to the Modeler palette, so it's not appearing in the Modeler to use in the BPMN process design.

**Comment by lsmall** [comment]
The data object is a property on the process or subprocess, not a visual element. I considered leaving the "items" element in the JSON property naming, but was trying to emulate the form properties syntax. I will verify it with the reverted syntax and open a new issue if it has problems. Thanks!

**Comment by tijsrademakers** [comment]
Ah right, now I understand. I've made a couple of changes locally to make it work. Will push them a bit later.

**Comment by lsmall** [comment]
Let me know when you are done and I will run a quick regression test.

**Comment by tijsrademakers** [comment]
Done with the changes

**Comment by lsmall** [comment]
No issues found in regression test. The exported BPMN syntax looks good and the unit test passed.

**Pull request merged**
