### PR TITLE
#3106 plain dmn table key export/import

### PR DESCRIPTION
**Pull request by martin-grofcik**
#### Check List:
* Unit tests: YES
* Documentation: YES - description hint in the modeler

### CODE REVIEW

**Comment by martin-grofcik** [comment]
@tijsrademakers @jbarrez @filiphr : Is there any reason why pull request is not merged?

**Comment by tijsrademakers** [comment]
@martin-grofcik , the discussion with this PR is if adding another property for filling in a static decision key can be confusing with the existing decision table reference property.

**Comment by martin-grofcik** [comment]
We are not able to define dmn key in dmnTask. Other tasks which use references allow reference by key. How to solve this problem and inconsistency?

**Comment by martin-grofcik** [comment]
Hi @tijsrademakers, may I ask you for your opinion?

**Comment by tijsrademakers** [comment]
Closing because Modeler is not part of Flowable 7 codebase.

**Pull request closed without merging**
