### PR TITLE
Increase exception message length from 255 characters to 2000

### PR DESCRIPTION
**Pull request by loic-seguin**

### CODE REVIEW

**Comment by loic-seguin** [comment]
This PR is linked to this issue https://github.com/flowable/flowable-engine/issues/3372 and this post on flowable forum https://forum.flowable.org/t/column-exception-msg-in-table-act-ru-deadletter-job-gets-truncated-to-255/9511

**Comment by tijsrademakers** [comment]
Did you test this against Oracle? Because it doesn't have 4000 characters there: https://github.com/flowable/flowable-engine/blob/c755db8381106a27d3ccd11f1458a3e486bd389f/modules/flowable-job-service/src/main/resources/org/flowable/job/service/db/create/flowable.oracle.create.job.sql#L21

**Comment by tijsrademakers** [comment]
@loic-seguin , it's not possible to change the column size in the database script for Oracle, because some versions of Oracle have a limitation to 2000 characters for text columns. I meant it as a reference that the value of the job info error message length can't be changed to 4000.

**Comment by loic-seguin** [comment]
ha ok I didn't know that...So 2000 characters will be fine then for me...I repush

**Comment by loic-seguin** [comment]
False positive on jdk 1.8 no ?

**Comment by filiphr** [comment]
Yes the JDK 8 failure is a false negative.

Just to make sure that this works on different DBs can you please add some tests as well? Have a look at the `ManagementService#getXXXExceptionStacktrace()` and where it is used for ideas where you can add the tests

**Comment by filiphr** [comment]
Btw, you can use `RandomStringUtils` from commons-lang3 in our tests to generate a large text message.

**Comment by loic-seguin** [comment]
I have written a test. Not sure how I can import org.apache.commons.lang.RandomStringUtils in the groovy script in the test though.

**Comment by filiphr** [comment]
@loic-seguin I think that easiest would be to pass the generated message as a variable in the process and use it in the script as a variable.

That way we won't need to have long lines as well :)

**Comment by loic-seguin** [comment]
Done

**Pull request merged**
