### PR TITLE
add multiple results property from decision tables to the DecisionTableVariableManager

### PR DESCRIPTION
**Pull request by vzickner**
#### Check List:
* Unit tests: YES
* Documentation: NA

### CODE REVIEW

**Review by yvoswillens — COMMENTED** [review]
@vzickner shouldn't the change also be applied to the `setDecisionServiceVariablesOnExecution`?

**Comment by vzickner** [comment]
Thanks @yvoswillens, I think you are right. I will do the change.

**Comment by vzickner** [comment]
Hi @yvoswillens, I added the same for decision services as well. Also, multiple results are now set for decision services in case there are multiple results (either through multiple decision tables or one decision table with multiple results).

**Comment by yvoswillens** [comment]
Thanks for the PR @vzickner !

**Pull request merged**
