### PR TITLE
Add support for unaqcuiring jobs on AsyncExecutor shutdown

### PR DESCRIPTION
**Pull request by enchobelezirev**
Relates to this forum post: https://forum.flowable.org/t/unacquire-jobs-when-asyncexecutor-shutdown-method-is-called/3855

Also, found that the unacquire method is called on the start of the AsyncExecutor. This PR, makes it to be called on the shutdown as well.

### CODE REVIEW

**Comment by enchobelezirev** [comment]
I have used the latest formatter included in the ide-settings folder :)

**Comment by enchobelezirev** [comment]
Hello @tijsrademakers,

Thanks for merging the PR. I have one question, though.
Why have you removed the if from the method?
In our case we do not have a tenantId and thus there is an Exception when using the method. 
In my opinion, the if check is needed there.

Best regards,
Encho

**Comment by enchobelezirev** [comment]
Here is the method from the JobQuery:
```
@Override
    public JobQuery jobTenantId(String tenantId) {
        if (tenantId == null) {
            throw new FlowableIllegalArgumentException("Provided tenant id is null");
        }
        this.tenantId = tenantId;
        return this;
    }
```

**Comment by enchobelezirev** [comment]
Moreover, the tenantId will always be null as the method unlockOwnedJobs is calling the UnacquireOwnedJobsCmd with tenantId = null:
`protected void unlockOwnedJobs() {
        jobServiceConfiguration.getCommandExecutor().execute(new UnacquireOwnedJobsCmd(lockOwner, null));
    }`

**Comment by jbarrez** [comment]
The tenantId, when not set is defaulting to the empty string, see https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java#L266 which references https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/AbstractEngineConfiguration.java#L92

Do you have custom changes that make this tenantId null?

**Comment by enchobelezirev** [comment]
No, but the problem is not that the tenantId is null in the AbstractEngineConfiguration, the problem is that the unlockOwnedJobs method in the AsyncExecutor is calling the UnacquireOwnedJobsCmd with tenantId = null. Please, see:
https://github.com/flowable/flowable-engine/blob/master/modules/flowable-job-service/src/main/java/org/flowable/job/service/impl/asyncexecutor/AbstractAsyncExecutor.java#L94

**Comment by jbarrez** [comment]
Ok, thanks. I understand the problem now. I'll apply a fix + add a test for this.

**Comment by enchobelezirev** [comment]
Hey @jbarrez, 
Is there any update on the fix in the UnacquireOwnedJobsCmd ?

**Comment by jbarrez** [comment]
@enchobelezirev : it seems I added it long time ago, but never pushed it. Apologies!
I'll merge your PR instead, thanks!

**Comment by enchobelezirev** [comment]
I thank you, too!

**Pull request merged**
