### PR TITLE
flowable entrypoint script and permission changes

### PR DESCRIPTION
**Pull request by im-pratham**
#### Check List:
* Unit tests:  NA
* Documentation:  NA

The changes are to allow image to run on Openshift container platform

### CODE REVIEW

**Review by yvoswillens — COMMENTED** [review]
Hi @im-pratham ,

Will the `554` mode fix the issue that Openshift will use a random user?
Will that user be part of the 'root group'?

Could you explain why switch with executing the command?
Will starting the `FlowableUiApplication` as the `flowable` user not suffice?

Regards,

Yvo

**Comment by im-pratham** [comment]
@yvoswillens refer https://docs.openshift.com/container-platform/4.3/openshift_images/create-images.html section *Support arbitrary user ids*, there it's mentioned as "the container user is always a member of the root group." 
I added double check for ensure the condition of root user where both user id and group id is 0

**Comment by im-pratham** [comment]
> 
> 
> Hi @im-pratham ,
> 
> Will the `554` mode fix the issue that Openshift will use a random user?
> Will that user be part of the 'root group'?
> 
> Could you explain why switch with executing the command?
> Will starting the `FlowableUiApplication` as the `flowable` user not suffice?
> 
> Regards,
> 
> Yvo

For starting as flowable user, su-exec is not permitted. I am getting error error as 
`su-exec: setgroups: Operation not permitted` even though I added 554 permission

**Comment by im-pratham** [comment]
@yvoswillens I am using openshift developer sandbox to test the changes - https://developers.redhat.com/developer-sandbox/get-started

**Comment by yvoswillens** [comment]
The image does not start without errors (outside open shift)

```
docker run --rm  -p8080:8080 impratham/flowable-ui
standard_init_linux.go:219: exec user process caused: no such file or directory
```

**Comment by im-pratham** [comment]
That's mistake from my side, latest points to malfunctioning image. It had CRLF line ending. Refer this image `docker run --rm  -p8080:8080 impratham/flowable-ui:6.7.0-SNAPSHOT`.

Until then I will fix the tags

**Comment by yvoswillens** [comment]
I'm happy with the first part of the change.
Less with the second.
I've to investigate a bit further how to support the use case of starting the container as root group member; but keep being able to start the main process as flowable user before merging this to master.

Will post progress here in this thread.

**Comment by im-pratham** [comment]
@yvoswillens for 2nd part I am having some ideas, let me know your thoughts.
We can USER directives in docker file to cater the non-openshift environments. ( Openshift ignores the USER directives, hence giving 554 permission will suffice). So we can remove su-exec dependency altogether, but I need to investigate further how it will work with base-image and jib-maven plugin

**Comment by yvoswillens** [comment]
I would prefer keep using su-exec. Let's see what is needed in order to execute that as root group member.

**Comment by im-pratham** [comment]
@yvoswillens any specific reason to go for su-exec than user directive from dockerfile?

**Comment by yvoswillens** [comment]
the way su-exec steps down from root has some benefits. But; rehashing it I see potential issues with OpenShift.
Could you prepare the PR with the USER alternative so that we can review it?

**Comment by im-pratham** [comment]
> the way su-exec steps down from root has some benefits. But; rehashing it I see potential issues with OpenShift.
> Could you prepare the PR with the USER alternative so that we can review it?

Sure

**Comment by im-pratham** [comment]
@yvoswillens few changes made after our discussion - 
1. Changed MAINTAINER to LABEL
2. Removed su-exec 
3. Granted permission to root group to app folder as per openshift guidelines
4. Granted 555 permission to flowable-entrypoint. (the files added via jib are owned by root:root. So to allow flowable user to execute entrypoint script I have to give exec permission to others)

Let me know your thoughts. I tested both images on openshift and local (Docker desktop for windows with WSL2 backend). To test you can use this image `impratham/flowable-ui:6.7.0-SNAPSHOT`

**Review by yvoswillens — APPROVED** [review]

**Comment by yvoswillens** [comment]
First checks looks good! I'll run some more from master.
Thanks for the PR @im-pratham !

Regards,

Yvo

**Pull request merged**
