### PR TITLE
 Upgrade to Spring Framework 5.0.8 and Spring Security 5.0.7

### PR DESCRIPTION
**Pull request by PascalSchumacher**
To make this possible the Java Persistence API has to be updated to version 2.1. This in turn requires an update of Hibernate (5.2.16) and the replacement of OpenJPA with Hibernate because no version of OpenJPA supports API 2.1.

`org.springframework.security.authentication.dao.SystemWideSaltSource` was removed in Spring Security 5, therefore `org.flowable.idm.spring.authentication.SpringSaltProvider` was removed.

`org.springframework.security.crypto.password.PasswordEncoder` was removed in Spring Security 5, therefore its usage in `org.flowable.idm.spring.authentication.SpringEncoder` was removed.

Native OpenJPA support was dropped in Spring 5, so the flowable-spring JPASpringTest test class was changed to use Hibernate instead.

To fix tests in flowable-content-rest and flowable-dmn-rest `NoOpPasswordEncoder` was added to the test configuration of these modules.

Flowable-rest hibernate test dependencies were updated to match Hibernate-Core 5.2.16.

Mule does not support Spring Security 5 yet, so the Spring Security version was overridden to make tests pass.

Flowable-jms-spring-executor was upgraded to JMS-API version 2.0.1, because Spring 5 requires JMS 2.0+.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
`org.springframework.security.crypto.password.PasswordEncoder` and `org.springframework.security.authentication.dao.SystemWideSaltSource` were removed in Spring Security 5. No sure what should be done with `SpringSaltProvider`?

Sadly the latest OpenJPA version  (2.4.2) only supports JPA 2.0 and seems to have problems on java 9. I guess the best option would be to switch to EclipseLink or Hibernate?

**Comment by tijsrademakers** [comment]
Hi Pascal, thanks for the work on the Spring upgrade you already did. For the 6.3.0 we will stay with Spring 4.x as a dependency for the default Spring modules. The Spring boot modules do use Spring 5.x, so at least we know the engines work with Spring 5 as well.
If all goes well, 6.3.0 will go out tomorrow. So we leave this for the next 6.3.1 release.

**Comment by PascalSchumacher** [comment]
Hi Tijs,

thanks for letting me know!

It is great that 6.3.0 will be released soon.

**Comment by PascalSchumacher** [comment]
Build should pass on travis. Locally all tests of the distro profile pass.

**Comment by PascalSchumacher** [comment]
Rebased onto latest master.

**Comment by filiphr** [comment]
Thanks for the PR @PascalSchumacher I have just merged it

**Comment by PascalSchumacher** [comment]
Thanks for merging! :smiley:

**Pull request merged**
