### PR TITLE
Add support for HANA databases

### PR DESCRIPTION
**Pull request by nictas**
#### Check List:
* Unit tests: NA
* Documentation: NO

This PR is not yet ready for merging. I'm opening it in case you have some early feedback, and so that other SAP colleagues can review it.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
@nictas thanks for the PR. One thing that needs to be changed is the version 6.3.2.0 that is used in the create sql scripts. This should be 6.5.1.0 on master. Maybe also the changes that were made since 6.3.2.0 are not included yet in the Hana create sql scripts?

**Comment by tijsrademakers** [comment]
Closing the PR for now. A Hana database need to be available in our QA to be able to support it. When this is possible the PR can be merged.

**Comment by guangping0215** [comment]
Hi @tijsrademakers ,
May I know about the state of this PR? Is it possible to release for supporting HANA database?
Thanks

**Comment by tijsrademakers** [comment]
Hi @guangping0215 , please check my last comment from August 24, 2021, we still don't have an option to run a Hana database in our QA environment.

**Pull request closed without merging**
