### PR TITLE
Changed the default tenant from empty string to null

### PR DESCRIPTION
**Pull request by 4gsim**
#2674 Flowable UI Modeler - Processes and Apps not displayed when using an Oracle database and no tenant

#### Check List:
* Unit tests: NA
* Documentation: NA

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks for doing this PR @4gsim.

The fix for the problem should be in the MyBatis XML for the Modeler, not in the logic of how the default tenant is set. The default tenant is the empty string on other DBs, it is only null in Oracle (because Oracle stores empty string as null)

**Comment by 4gsim** [comment]
How can you fix the problem in the XML only for Oracle?
What is the reason for the default tenant being an empty string and not null?

**Comment by filiphr** [comment]
>How can you fix the problem in the XML only for Oracle?

We have a lot of places in the XMLs where we do `(tenant_id = '' or tenant_id is null)`. In order to be consistent we need to do it like that for the modeler as well.


>What is the reason for the default tenant being an empty string and not null?

This is mostly a legacy reason. The tenant id has been an empty string fro years. We cannot easily change it without big migrations and we want to avoid such migrations.

**Comment by 4gsim** [comment]
There are a lot of cases in the xml files where this check is not done. Should we do this only for the modeler xml?

**Comment by filiphr** [comment]
Can you give examples? There are some queries when you pass a tenant id, where we do not do this. However, in those queries there is `withoutTenantId` that does this. We are quite confident that the XMLs for the engines are good 😄 .

**Comment by 4gsim** [comment]
For example for the ProcessDefinition.xml
`       <if test="tenantId != null">
        and RES.TENANT_ID_ = #{tenantId}
      </if>
      <if test="tenantIdLike != null">
        and RES.TENANT_ID_ like #{tenantIdLike}${wildcardEscapeClause}
      </if>
      <if test="withoutTenantId">
        and (RES.TENANT_ID_ = '' or RES.TENANT_ID_ is null)
      </if>`
You are right there is a withoutTenantId flag, but it is it automatically linked to the tenantId variable, or you have to set it manually in the query? If you don't set it and set the tenantId to empty string you will get the same behavior.

**Comment by filiphr** [comment]
>You are right there is a withoutTenantId flag, but it is it automatically linked to the tenantId variable, or you have to set it manually in the query? If you don't set it and set the tenantId to empty string you will get the same behavior.
Should there be the same implementation for the model xml?

You have to manually invoke `ProcessDefinitionQuery#withoutQuery`. Usually when querying by tenant id you should decide whether you want to search for entities without a query, or you want to search for entities with a specific tenant id. We don't need to change anything here.

**Comment by 4gsim** [comment]
I meant if for the Modeler xml we should do a similar implementation with 'withoutTenantId' flag?

**Comment by filiphr** [comment]
Sorry I misunderstood you. No we don't need to do that for the Modeler. I think that it is enough to do it directly in the XML when the tenantId is the empty string. The Modeler is an end user application, not an API that someone else can use it

**Comment by PascalSchumacher** [comment]
@filiphr Any updates? (It would be great to have this fix in the next flowable version imho.)

**Comment by filiphr** [comment]
@PascalSchumacher, I was just in the process of merging this

**Pull request merged**
