### PR TITLE
Use {} in logging instead of string concatenation

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Made a pass through the source files replacing string concatenation in logging messages to use {} instead.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi David, thanks for commit. Could you also resolve the conflicts for this PR?

**Comment by dbmalkovsky** [comment]
Tijs,  I think I've run all the tests that I can and believe that this is finally clean and merged.  Sorry it took so long.

**Comment by dbmalkovsky** [comment]
Tijs,
Once again the merge is done and everything compiles and tests clean.

**Comment by dbmalkovsky** [comment]
Geez, I thought I had reread all the changes twice. Sorry about that. :(

**Comment by tijsrademakers** [comment]
Np, understand it's easy to miss when you are doing so many {} changes :-)

**Pull request merged**
