### PR TITLE
Close database connections used by Liquibase (#950)

### PR DESCRIPTION
**Pull request by PascalSchumacher**
No sure if the spring part of the fix (4fab177c76b3c09be50423e81d96a220ccbd76a9) is correct.

Are the `liquibase` beans supposed to be used, or are they just for initialization?

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@filiphr  Good point! I have updated the pull request.

**Comment by PascalSchumacher** [comment]
>However, I think that we need to set the liquibase database connection to null in case the connection was fetched from the command context.

This is not possible, because it will lead to exceptions in liquibase, therefore we have to skip the clean up in this case.

**Comment by filiphr** [comment]
>Sadly this is not possible, as it will lead to exceptions in liquibase. Therefore we have to skip the clean up in this case.

What kind of exceptions? The thing is that the `XXXDbSchemaManager`(s) are invoked from within a command context always, which means that the database close won't be invoked ever now.

**Comment by PascalSchumacher** [comment]
`liquibase.database.Database` does not have a setter to set the `Connection` to `null`. Therefore we have to construct a new `Database` instance and that does not work if we pass it a `null` `Connection`.

**Comment by PascalSchumacher** [comment]
The only way I found to keep liquibase from closing the `Connection` is:

```java
if (CommandContextUtil.getCommandContext() != null) {
    database.setConnection(new JdbcConnection(null));
}
try {
    database.close();
} catch (DatabaseException e) {
    LOGGER.warn("Error closing database", e);
}
```
But this results in `NullPointerExceptions`, e.g:

```
[ERROR] org.flowable.cmmn.test.tenant.MultiTenantTest  Time elapsed: 0.106 s  <<< ERROR!
org.flowable.common.engine.api.FlowableException: Error initialising cmmn data model
        at org.flowable.cmmn.engine.impl.db.CmmnDbSchemaManager.initSchema(CmmnDbSchemaManager.java:69)
        at org.flowable.cmmn.engine.impl.db.CmmnDbSchemaManager.initSchema(CmmnDbSchemaManager.java:47)
        at org.flowable.cmmn.engine.impl.db.CmmnDbSchemaManager.initSchema(CmmnDbSchemaManager.java:43)
        at org.flowable.cmmn.engine.impl.cmd.SchemaOperationsCmmnEngineBuild.execute(SchemaOperationsCmmnEngineBuild.java:27)
        at org.flowable.cmmn.engine.impl.cmd.SchemaOperationsCmmnEngineBuild.execute(SchemaOperationsCmmnEngineBuild.java:23)
        at org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker$1.run(CmmnCommandInvoker.java:46)
        at org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.executeOperations(CmmnCommandInvoker.java:70)
        at org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.execute(CmmnCommandInvoker.java:49)
        at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
        at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71)
        at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:35)
        at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
        at org.flowable.cmmn.engine.impl.CmmnEngineImpl.<init>(CmmnEngineImpl.java:59)
        at org.flowable.cmmn.engine.CmmnEngineConfiguration.buildCmmnEngine(CmmnEngineConfiguration.java:658)
        at org.flowable.cmmn.engine.test.FlowableCmmnTestCase.initCmmnEngine(FlowableCmmnTestCase.java:71)
        at org.flowable.cmmn.engine.test.FlowableCmmnTestCase.setupEngine(FlowableCmmnTestCase.java:64)
        at sun.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.NullPointerException
        at liquibase.database.jvm.JdbcConnection.getConnectionUserName(JdbcConnection.java:85)
        at liquibase.database.AbstractJdbcDatabase.setConnection(AbstractJdbcDatabase.java:125)
        at liquibase.database.core.H2Database.setConnection(H2Database.java:287)
        at org.flowable.cmmn.engine.impl.db.CmmnDbSchemaManager.closeDatabase(CmmnDbSchemaManager.java:234)
        at org.flowable.cmmn.engine.impl.db.CmmnDbSchemaManager.dbSchemaUpdate(CmmnDbSchemaManager.java:203)
        at org.flowable.cmmn.engine.impl.db.CmmnDbSchemaManager.initSchema(CmmnDbSchemaManager.java:61)
        ... 31 more
```

**Comment by PascalSchumacher** [comment]
It would be great if this could be part of the next release.

**Comment by tijsrademakers** [comment]
Sorry for the delay Pascal, thanks for the PR

**Comment by PascalSchumacher** [comment]
No problem :smile:.

Thanks for merging! :+1:

**Pull request merged**
