### PR TITLE
Terminate end event fix

### PR DESCRIPTION
**Pull request by martin-grofcik**

### CODE REVIEW

**Comment by roberthafner** [comment]
Hi Martin,

My colleague noticed a regression was introduced in PR (https://github.com/flowable/flowable-engine/pull/320) and submitted a PR (https://github.com/flowable/flowable-engine/pull/331) with a test case to show the regression.  Do you know if PR 330 resolves this issue? Based on a quick glance I suspect it doesn't. 

thanks,
Rob

**Comment by martin-grofcik** [comment]
Hi Rob,

I have tested #331 with proposed changes. The test passes. 
Thanks. 
Martin

**Comment by roberthafner** [comment]
Thanks Martin! We will pull in the changes once its merged.

Rob

**Comment by stephraleigh** [comment]
Hi Martin,  
Just wanted to let you know there is still one outstanding regression that resulted in the 320/330 changes. I pushed a test case that reproduces the issue #336 
Steph

**Pull request merged**
