### PR TITLE
Modifiers should be specified in the canonical preferred order

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Addresses issue #3 from the [standards forum post](http://forum.flowable.org/t/coding-style-and-standards/154).

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi David, in the REST resources @ResponseBody seems to have been moved in the wrong place, or was this on purpose?

**Comment by dbmalkovsky** [comment]
Just following the [Spring docs](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-responsebody) where they put in on the method itself.  I can undo this if you don't want it.

**Comment by tijsrademakers** [comment]
Right, see it as well. In the Spring docs it's placed under the @RequestMapping notation instead of above, maybe we should follow that pattern as well?

**Comment by dbmalkovsky** [comment]
Can be (and will be) done; it will have to wait until tomorrow; sorry.

**Comment by dbmalkovsky** [comment]
Tijs,
I moved the location of the @ResponseBody annotations and in the process made the commenting of return code values more consistent.

**Comment by tijsrademakers** [comment]
thanks

**Pull request merged**
