### PR TITLE
Upgrade to Spring Boot 2.5.2

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Clean build locally: `mvn clean test`.

Here are the Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.

All the dependencies I could find have been updated.

Sorry about all the formatting changes in the pom.xml; I can't seem to get rid of them.

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks @dbmalkovsky. It seems everything is working fine now. I'll integrate this manually in order to fix the formatting changes.

**Comment by dbmalkovsky** [comment]
@filiphr I think the problem is that the pom.xml is a mixture of tabs and spaces and when I saved the file it changed it all to just tabs.  I'm trying another way.

**Comment by dbmalkovsky** [comment]
@filiphr Found a way to only make the changes required.  You should be able to commit directly.

**Comment by filiphr** [comment]
Thanks @db

**Pull request merged**
