### PR TITLE
Update to Camel 3

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Camel `3.0.0` was just released. Support for Camel `2.x` will end soon.

This pull request updates the `flowable-camel` and the `flowable-camel-cdi` modules to use the new Camel 3 API.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
@PascalSchumacher this PR can be closed right?

**Comment by PascalSchumacher** [comment]
It can't be merge at them moment, but the changes are relevant when flowable updates to Camel 3.x.

**Comment by PascalSchumacher** [comment]
Pull request update to use the release version of Camel 3.

**Comment by PascalSchumacher** [comment]
Any chance for this to be part of the next flowable release?

**Comment by PascalSchumacher** [comment]
Should I update the pull request to add two new modules `flowable-camel3` and `flowable-camel3-cdi` instead of changing the existing modules?

**Comment by tijsrademakers** [comment]
@PascalSchumacher would you have time to look into the Camel 3 upgrade again? Will close this PR for now.

**Comment by PascalSchumacher** [comment]
The update was working for Camel 3.0.0. The current version 3.11.0 would require further changes.

I did not work on further updates as I did not receive any feedback on this pull request more than 1,5 years.

I do know when/if I have the time to work on this.

Would you merge the pull request if I were to update it to work with current Camel 3?

**Comment by tijsrademakers** [comment]
Fully understand, and sorry for the lack of communication before.
We will proceed with the 6.7 release now, but for 6.8 an upgrade to Camel 3 would be great if you have time.

**Pull request closed without merging**
