### PR TITLE
Sybase ASE support

### PR DESCRIPTION
**Pull request by delchev**
Adding support for SAP Sybase ASE database.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Thanks for the PR. We need to setup a Sybase database in our QA environment before we can merge this PR. So it will need a bit more time than usual.

**Comment by delchev** [comment]
I will try to prepare a step by step guide how to setup a test environment using only publicly available resources.

**Comment by delchev** [comment]
How to setup a test environment for Flowable with Sybase on Amazon
---

### Select Image Size:
	t2.medium

### Security Group:
	TCP Custom, 5000

### Download Sybase ASE Express
       https://www.sap.com/cmp/syb/crm-xu15-int-asexprdm/index.html
### Transfer:
	> scp -i flowable-aws.pem ASE_Suite.linuxamd64.tgz ec2-user@<ip-address>:~
	> scp -i flowable-aws.pem apache-maven-3.5.2-bin.tar.gz ec2-user@<ip-address>:~
	> scp -i flowable-aws.pem flowable-engine.zip ec2-user@<ip-address>:~
	> scp -i flowable-aws.pem jdk-8u144-linux-x64.tar.gz ec2-user@<ip-address>:~

### Prepare OS:
	> sudo mkdir -p /opt/sybase
	> sudo mkdir -p /var/sybase
	> sudo groupadd sybase
	> sudo useradd -g sybase -d /opt/sybase sybase
	> sudo passwd sybase
	> sudo chown sybase:sybase /opt/sybase
	> sudo chown sybase:sybase /var/sybase
### Login:
	> ssh ec2-user@<ip-address> -i flowable-aws.pem

### Setup:
	> su - sybase
	> mkdir install
	> cd install
	> cp /home/ec2-user/ASE_Suite.linuxamd64.tgz .
	> tar -xvf ASE_Suite.linuxamd64.tgz
	> ./setup.bin -i console

### Parameters:
	Choose Install Folder -> use: /opt/sybase
	Choose Install Set -> 1- Typical
	Software License Type Selection -> 2- Install Express Edition of SAP Adaptive Server Enterprise
	End-user License Agreement -> 1) All regions
	Configure New Servers -> [X] 1 -  Configure new SAP ASE
	Configure Servers with Different User Account -> 2- No
	SAP ASE Name                                  ASE160
	System Administrator's Password               ******
	Enable SAP ASE for SAP ASE Cockpit monitoring false
	Technical user                                tech_user
	Technical user password                       ********
	Host Name                                     ip-<internal-ip-address>.eu-central-1.comp
	Port Number                                   5000
	Application Type                              Mixed (OLTP/DSS)
	Create sample databases                       false
	Page Size                                     4k
	Error Log                                     /opt/sybase/ASE-16_0/install/ASE1
	Default Language                              <use default>
	Default Character Set                         <use default>
	Default Sort Order                            <use default>
	Master Device                                 /opt/sybase/data/master.dat
	Master Device Size (MB)                       500
	Master Database Size (MB)                     250
	System Procedure Device                       /opt/sybase/data/sysprocs.dat
	System Procedure Device Size (MB)             500
	System Procedure Database Size (MB)           500
	System Device                                 /opt/sybase/data/sybsysdb.dat
	System Device Size (MB)                       100
	System Database Size (MB)                     100
	Tempdb Device                                 /opt/sybase/data/tempdbdev.dat
	Tempdb Device Size (MB)                       1000
	Tempdb Database Size (MB)                     1000
	Enable PCI                                    false
	Optimize SAP ASE Configuration                false

### Show Servers:
	> /opt/sybase/ASE-16_0/install/showserver

### Prepare Test Environment:
	> cd /opt/sybase/install
	> cp /home/ec2-user/flowable-engine.zip .
	> cp /home/ec2-user/apache-maven-3.5.2-bin.tar.gz .
	> cp /home/ec2-user/jdk-8u144-linux-x64.tar.gz .
	> unzip flowable-engine.zip
	> tar -xvf apache-maven-3.5.2-bin.tar.gz
	> tar -xvf jdk-8u144-linux-x64.tar.gz
	> export JAVA_HOME=/opt/sybase/install/jdk1.8.0_144

### Add the provided JDBC driver to the local Maven repository:
	> /opt/sybase/install/apache-maven-3.5.2/bin/mvn install:install-file -Dfile=/opt/sybase/shared/lib/jconn4.jar -DgroupId=com.sybase.jdbc4 -DartifactId=jconn4 -Dversion=6.0.SP02 -Dpackaging=jar

### Change test configuration:
	> cd /opt/sybase/install/flowable-engine/modules/flowable-engine/src/test/resources/

	modify flowable.cfg.xml

		<property name="jdbcUrl" value="jdbc:sybase:Tds:<ip-address>:5000" />
		<property name="jdbcDriver" value="com.sybase.jdbc4.jdbc.SybDriver" />
		<property name="jdbcUsername" value="sa" />
		<property name="jdbcPassword" value="sybase" />

	> cd /opt/sybase/install/flowable-engine/modules/flowable-engine
	
	modify pom.xml to add dependency as follows:

       <dependency>
            <groupId>com.sybase.jdbc4</groupId>
            <artifactId>jconn4</artifactId>
            <version>6.0.SP02</version>
            <scope>test</scope>
       </dependency>

### Run Tests:
	> cd /opt/sybase/install/flowable-engine
	> /opt/sybase/install/apache-maven-3.5.2/bin/mvn clean install

Useful actions in case of issues
---

### Start Server:
	> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/sybase/OCS-16_0/lib3p64
	> export LANG=C
	> cd /opt/sybase/ASE-16_0/bin
	> ./startserver -f /opt/sybase/ASE-16_0/install/RUN_ASE160

### Stop Server:
	> cd /opt/sybase/OCS-16_0/bin
	> export LANG=C
	> ./isql -Usa -SASE160
	$> shutdown with nowait
	$> go

### Kill Hanging Requests:
	> cd /opt/sybase/OCS-16_0/bin
	> export LANG=C
	> ./isql -Usa -SASE160
	1> sp_who
	2> go
	1> kill spid

### Uninstall:
	> cd /opt/sybase/sybuninstall/ASESuite
	> ./uninstall -i console

**Comment by delchev** [comment]
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] org.flowable.engine.test.api.history.HistoricTaskAndVariablesQueryTest.testQueryWithPagingAndVariables(org.flowable.engine.test.api.history.HistoricTaskAndVariablesQueryTest)
[ERROR]   Run 1: HistoricTaskAndVariablesQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryWithPagingAndVariables:505 expected:<2> but was:<1>
[ERROR]   Run 2: HistoricTaskAndVariablesQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryWithPagingAndVariables:505 expected:<2> but was:<1>
[ERROR]   Run 3: HistoricTaskAndVariablesQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryWithPagingAndVariables:505 expected:<2> but was:<1>
[INFO] 
[ERROR] org.flowable.engine.test.api.history.HistoricTaskAndVariablesQueryTest.testQueryWithPagingVariablesAndIdentityLinks(org.flowable.engine.test.api.history.HistoricTaskAndVariablesQueryTest)
[ERROR]   Run 1: HistoricTaskAndVariablesQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryWithPagingVariablesAndIdentityLinks:537 expected:<2> but was:<1>
[ERROR]   Run 2: HistoricTaskAndVariablesQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryWithPagingVariablesAndIdentityLinks:537 expected:<2> but was:<1>
[ERROR]   Run 3: HistoricTaskAndVariablesQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryWithPagingVariablesAndIdentityLinks:537 expected:<2> but was:<1>
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ExecutionQueryTest.testExecutionQueryWithProcessVariable(org.flowable.engine.test.api.runtime.ExecutionQueryTest)
[ERROR]   Run 1: ExecutionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testExecutionQueryWithProcessVariable:1450 expected:<3> but was:<6>
[ERROR]   Run 2: ExecutionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testExecutionQueryWithProcessVariable:1450 expected:<3> but was:<6>
[ERROR]   Run 3: ExecutionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testExecutionQueryWithProcessVariable:1450 expected:<3> but was:<6>
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ExecutionQueryTest.testQueryEqualsIgnoreCase(org.flowable.engine.test.api.runtime.ExecutionQueryTest)
[ERROR]   Run 1: ExecutionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryEqualsIgnoreCase:422
[ERROR]   Run 2: ExecutionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryEqualsIgnoreCase:422
[ERROR]   Run 3: ExecutionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryEqualsIgnoreCase:422
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest.testOrQueryByDeploymentId(org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest)
[ERROR]   Run 1: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testOrQueryByDeploymentId:378 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 2: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testOrQueryByDeploymentId:378 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 3: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testOrQueryByDeploymentId:378 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest.testOrQueryByDeploymentIdIn(org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest)
[ERROR]   Run 1: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testOrQueryByDeploymentIdIn:439 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 2: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testOrQueryByDeploymentIdIn:439 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 3: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testOrQueryByDeploymentIdIn:439 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest.testQueryByDeploymentId(org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest)
[ERROR]   Run 1: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByDeploymentId:352 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 2: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByDeploymentId:352 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 3: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByDeploymentId:352 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest.testQueryByDeploymentIdIn(org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest)
[ERROR]   Run 1: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByDeploymentIdIn:366 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 2: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByDeploymentIdIn:366 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[ERROR]   Run 3: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByDeploymentIdIn:366 expected:<oneTaskProcess[]> but was:<oneTaskProcess[2]>
[INFO] 
[ERROR] org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest.testQueryEqualsIgnoreCase(org.flowable.engine.test.api.runtime.ProcessInstanceQueryTest)
[ERROR]   Run 1: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryEqualsIgnoreCase:1561
[ERROR]   Run 2: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryEqualsIgnoreCase:1561
[ERROR]   Run 3: ProcessInstanceQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryEqualsIgnoreCase:1561
[INFO] 
[ERROR] org.flowable.engine.test.api.task.TaskDueDateTest.testDueDateSortingWithNulls(org.flowable.engine.test.api.task.TaskDueDateTest)
[ERROR]   Run 1: TaskDueDateTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testDueDateSortingWithNulls:60
[ERROR]   Run 2: TaskDueDateTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testDueDateSortingWithNulls:60
[ERROR]   Run 3: TaskDueDateTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testDueDateSortingWithNulls:60
[INFO] 
[ERROR] org.flowable.engine.test.api.task.TaskQueryTest.testProcessVariableValueLike(org.flowable.engine.test.api.task.TaskQueryTest)
[ERROR]   Run 1: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testProcessVariableValueLike:1803 expected:<0> but was:<1>
[ERROR]   Run 2: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testProcessVariableValueLike:1803 expected:<0> but was:<1>
[ERROR]   Run 3: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testProcessVariableValueLike:1803 expected:<0> but was:<1>
[INFO] 
[ERROR] org.flowable.engine.test.api.task.TaskQueryTest.testTaskVariableValueEquals(org.flowable.engine.test.api.task.TaskQueryTest)
[ERROR]   Run 1: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTaskVariableValueEquals:1470 expected:<0> but was:<1>
[ERROR]   Run 2: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTaskVariableValueEquals:1470 expected:<0> but was:<1>
[ERROR]   Run 3: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTaskVariableValueEquals:1470 expected:<0> but was:<1>
[INFO] 
[ERROR] org.flowable.engine.test.api.task.TaskQueryTest.testTaskVariableValueEqualsOr(org.flowable.engine.test.api.task.TaskQueryTest)
[ERROR]   Run 1: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTaskVariableValueEqualsOr:1555 expected:<0> but was:<1>
[ERROR]   Run 2: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTaskVariableValueEqualsOr:1555 expected:<0> but was:<1>
[ERROR]   Run 3: TaskQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTaskVariableValueEqualsOr:1555 expected:<0> but was:<1>
[INFO] 
[ERROR] org.flowable.engine.test.bpmn.deployment.BpmnDeploymentTest.testDeploySameFileTwiceAfterInitialDeployment(org.flowable.engine.test.bpmn.deployment.BpmnDeploymentTest)
[ERROR]   Run 1: BpmnDeploymentTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testDeploySameFileTwiceAfterInitialDeployment:169 expected:<2> but was:<3>
[ERROR]   Run 2: BpmnDeploymentTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testDeploySameFileTwiceAfterInitialDeployment:169 expected:<2> but was:<3>
[ERROR]   Run 3: BpmnDeploymentTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testDeploySameFileTwiceAfterInitialDeployment:169 expected:<2> but was:<3>
[INFO] 
[ERROR] org.flowable.examples.mgmt.ManagementServiceTest.testTableCount(org.flowable.examples.mgmt.ManagementServiceTest)
[ERROR]   Run 1: ManagementServiceTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTableCount:53 expected:<10> but was:<8>
[ERROR]   Run 2: ManagementServiceTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTableCount:53 expected:<10> but was:<8>
[ERROR]   Run 3: ManagementServiceTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testTableCount:53 expected:<10> but was:<8>
[INFO] 
[ERROR] Errors: 
[ERROR] org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest.testQueryByActivityId(org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest)
[ERROR]   Run 1: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByActivityId:104 ? Persistence
[ERROR]   Run 2: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByActivityId:104 ? Persistence
[ERROR]   Run 3: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByActivityId:104 ? Persistence
[INFO] 
[ERROR] org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest.testQueryByEventName(org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest)
[ERROR]   Run 1: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventName:40 ? Persistence
[ERROR]   Run 2: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventName:40 ? Persistence
[ERROR]   Run 3: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventName:40 ? Persistence
[INFO] 
[ERROR] org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest.testQueryByEventSubscriptionId(org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest)
[ERROR]   Run 1: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventSubscriptionId:139 ? Persistence
[ERROR]   Run 2: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventSubscriptionId:139 ? Persistence
[ERROR]   Run 3: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventSubscriptionId:139 ? Persistence
[INFO] 
[ERROR] org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest.testQueryByEventType(org.flowable.engine.test.api.nonpublic.EventSubscriptionQueryTest)
[ERROR]   Run 1: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventType:72 ? Persistence
[ERROR]   Run 2: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventType:72 ? Persistence
[ERROR]   Run 3: EventSubscriptionQueryTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testQueryByEventType:72 ? Persistence
[INFO] 
[WARNING] Flakes: 
[WARNING] org.flowable.engine.test.concurrency.ConcurrentEngineUsageTest.testConcurrentUsage(org.flowable.engine.test.concurrency.ConcurrentEngineUsageTest)
[ERROR]   Run 1: ConcurrentEngineUsageTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testConcurrentUsage:64 expected:<0> but was:<3>
[INFO]   Run 2: PASS
[INFO] 
[WARNING] org.flowable.engine.test.jobexecutor.ResetExpiredJobsTest.testResetExpiredJobTimeout(org.flowable.engine.test.jobexecutor.ResetExpiredJobsTest)
[ERROR]   Run 1: ResetExpiredJobsTest>AbstractFlowableTestCase.runBare:121->AbstractTestCase.runTest:60->testResetExpiredJobTimeout:124 expected:<1> but was:<0>
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
[ERROR] Tests run: 2132, Failures: 15, Errors: 4, Skipped: 0, Flakes: 2

**Comment by tijsrademakers** [comment]
Closing outdated PRs

**Pull request closed without merging**
