### PR TITLE
Fixing empty or condition when there are no candidateGroups

### PR DESCRIPTION
**Pull request by ilgrosso**
Background information: https://forum.flowable.org/t/sql-exception-with-task-query-after-upgrade-to-6-7-0/8334

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks for the PR @ilgrosso, I was already working on it and added some more tests for it as well

**Comment by ilgrosso** [comment]
@filiphr I see, sounds good.

Do you think such a fix is going to be released soon with - say - 6.7.1?

**Comment by filiphr** [comment]
I am not sure @ilgrosso, we will need to look into this. In any case I have posted a workaround for this in the forum question.

Instead of

```
taskService.createTaskQuery()..taskCandidateOrAssigned(authUser).list();
```

You can do

```
taskService.createTaskQuery.or().taskCandidateUser(authUser).taskAssignee(authUser).endOr().list();
```

It is a bit more verbose, but it is doable.

**Comment by ilgrosso** [comment]
@filiphr yep I did already applied the suggested workaround and I confirm it works as expected.

**Pull request closed without merging**
