### PR TITLE
  Fix Swagger/OpenAPI queryVariable operation enum case

### LINKED ISSUE #1437: Unsupported variable query operation: EQUALS
flowable-rest.war 6.4.0 
POST /query/historic-process-instances
when the parameters like :
{
  "variables": [
    {
      "name": "applyUserId",
      "operation": "EQUALS",
      "value": {},
      "type": "string",
      "variableOperation": "EQUALS"
    }
  ]
}

the respose is :
{
  "message": "Bad request",
  "exception": "Unsupported variable query operation: EQUALS"
}

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Fixes "Unsupported variable query operation: EQUALS" (fixes #1437)

Not sure this is correct, my knowledge of Swagger/OpenAPI is limited.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Any feedback on this pull request?

**Comment by PascalSchumacher** [comment]
Build failed on Java 9 and 10 because it took to long. I guess #1595 need to be merged first.

**Comment by filiphr** [comment]
@PascalSchumacher I think this is not the most correct place for the change. That file is semi automatic generated. I think that we need to annotated the `QueryVariable#operation` with Swagger annotations for the correct name. 

The correct names are defined in the [JSON query variable format](https://www.flowable.org/docs/userguide/index.html#restQueryVariable) section of the documentation. They are camelCase.

**Comment by PascalSchumacher** [comment]
@filiphr Thank you very much!

I have updated the pull request. 

The `flowable-swagger-process.yaml` generated by `flowable-oas-generator` now seems to be correct (as far as I can tell).

By the way: There is a third `QueryVariable` class located in the `flowable-ui-task-logic` module, but that module does not have a `swagger-annotations` dependency, so I did not update this class.

**Pull request merged**
