### PR TITLE
fixes #3360: Streamlined clone method calls

### LINKED ISSUE #3360: ExtensionElement#clone does not clone extensionElements field
**Describe the bug**
The ExtensionElement#clone method from both CMMN and BPMN modules do not clone extensionElements list derived from the super class BaseElement.

**Expected behavior**
clone() should make deep copy of every container attributes.

We can probably copy other super class fields like id too. Let me know your thoughts, would be happy to contribute the fix.

### PR DESCRIPTION
**Pull request by im-pratham**
Fixes #3360 

#### Check List:
* Unit tests: NA
* Documentation: NO

### CODE REVIEW

**Comment by filiphr** [comment]
Changes look good @im-pratham. Can you please remove the extra new lines you have pushed in `ProcessTask`, `Sentry`, `SentryOnPart`, `TimerEventListener` and `VariableEventListener`. I know that it comes from the auto format, but ideally PRs should not contain formatting changes.

Thanks @im-pratham

**Comment by im-pratham** [comment]
@filiphr added those on-purpose. But agree with your point, The PR has to be for only one specific functionality. Reverted the five files in latest commit.

**Comment by filiphr** [comment]
Thanks @im-pratham, really appreciated. Will merge this once the CI is done

**Comment by filiphr** [comment]
Thanks @im-pratham. This has been merged

**Pull request merged**
