### PR TITLE
Add support for CamelBehavior in CDI environment (Issue #538)

### PR DESCRIPTION
**Pull request by ruzkant**
Note there are some tests that don't pass but it is unrelated to the contributed code. AsyncProcessRevisitedTest fails regularly and MultiInstanceTest has failed on rare occasion

There were 3 options:
1. Add to flowable-camel and add optional CDI dependencies.
2. Add to flowable-cdi and add optional camel dependencies.
3. Create a new flowable-camel-cdi module.

Option 1 was chosen as the test code more naturally fits with flowable-camel, and conceptually CDI is a broader module and best to not depend on more specific module. This has its downsides. Some CDI test infrastructure code was minimally duplicated to avoid dependency on flowable-cdi test jar. Note also that CDI tests were failing when executed in the same process as Spring tests, due to the way ProcessEngines are loaded and accessed on startup. The current solution is to use two separate executions for the maven surefire plugin, one for spring tests and one for CDI tests.

### CODE REVIEW

**Comment by ruzkant** [comment]
Linking Issue: #538

**Comment by ruzkant** [comment]
One more comment, I wasn't sure about serialVersionUID for the behaviour implementation classes. I upped them by one as it seems that it had been done before for the default one.

**Comment by tijsrademakers** [comment]
@ruzkant thanks for the PR. A separate flowable-camel-cdi module would be a better fit for the current project modules to my opinion. Would it be possible for you to update the PR with a new module? The serialVersionUIDs don't need to be upped.

Thanks!

**Comment by ruzkant** [comment]
@tijsrademakers I'll do that. The only downside for that option was some tests overlap with the camel module which led me to value proximity for changes to those. But none of the options had no downsides for me, and this is definitely conceptually better.

**Comment by ruzkant** [comment]
@tijsrademakers no worries. I asked initially but as I progressed I thought I should maybe ask again and didn't :)

**Comment by ruzkant** [comment]
@tijsrademakers I have completed the refactoring into a separate module and reverted the serialVersionUID changes

**Pull request merged**
