### PR TITLE
Bug 1806: testcase and bugfix proposal

### PR DESCRIPTION
**Pull request by mwerlitz**
Changed getting the JPA entity identifier from reflection to JPA 2.0 API.
This way is compatible with entity proxy objects.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi,

Thanks for the PR. If this change runs fine with our test suite then it looks fine for me. Can we set it to ready for review, so travis will run all tests for this PR?

Thanks,

Tijs

**Comment by mwerlitz** [comment]
Hi Tijs,

two things to note about the fix:
- After the change Flowable will require a JPA 2.0 provider. If you need to support JPA 1.0 also we will need a version detection to fall back to the original implementation.
- The proposed fix does not modify the Flowable5 Engine (for compatibility)

**Comment by tijsrademakers** [comment]
Closing the PR. For this to be added a choice between a JPA 1.0 and 2.0 needs to be provided so that a Flowable user can choose how to run the JPA integration.

**Comment by mwerlitz** [comment]
I don't think just closing the PR for a bug that breaks current JPA integration is not an appropriate solution.

I could add a JPA version detection so there is no need for the user to explicitly decide between JPA 1.0 and 2.0 integration.
Furthermore as I remember correctly your build currently uses JPA 2.0 libs so there is no real JPA 1.0 compatiability anyway.

**Pull request closed without merging**
