### PR TITLE
Update Jackson to version 2.12.1.

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Spring Boot 2.4 supports Jackson 2.12, so this update should be possible.

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
Some of the failures are:
````
java.lang.IllegalArgumentException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
````
which indicates adding this `dependency` may help:
````
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
    <version>${jackson.version}</version>
</dependency>
````

**Comment by dbmalkovsky** [comment]
@PascalSchumacher when I pulled your PR and added the jar as noted above I got a clean build and test.

**Comment by PascalSchumacher** [comment]
@dbmalkovsky Thanks, but the question is: Why is jackson-datatype-jsr310 required when using Jackson 2.12?

On further thinking I believe it is best to wait with the update until Spring Boot uses Jackson 2.12 too.

**Comment by PascalSchumacher** [comment]
I guess this is the reason for the test failures: https://github.com/FasterXML/jackson-databind/issues/2683

**Pull request closed without merging**
